name: Run PIB Nowcast

on:
  schedule:
    - cron: '5 12 * * 1-5'   # 09:05 BRT
    - cron: '5 13 * * 1-5'   # 10:05 BRT
    - cron: '30 15 * * 1-5'  # 12:30 BRT
    - cron: '30 21 * * 1-5'  # 18:30 BRT
  workflow_dispatch:        # permite rodar manualmente

jobs:
  run_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run model creation script
        run: python model_creation.py

      - name: Commit updated model files (if changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add initial_model.pkl.gz initial_dataset.pkl.gz || true
          git diff --cached --quiet && echo "Nenhuma mudan√ßa detectada" || (
            git commit -m "Atualiza modelo e dataset automaticamente [skip ci]" && git push
          )
